version: "3.9"

services:
  backend:
    container_name: backend
    build: ./backend
    ports:
      - "3000:3000" # Map container port 3000 to host port 3000
    networks:
      - csec

  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "3001:3000" # Map container port 80 to host port 80
    networks:
      - csec

  # MySQL database service configuration
  mysql:
    container_name: csec-mysql
    image: mysql:8.0
    environment:
      # MYSQL_DATABASE: covid
      # MYSQL_USER: root
      # MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql 
    networks:
      csec:
        # ipv4_address: 172.25.0.3
    ports:
      - 3306:3306
networks:
  csec:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.25.0.0/16"
volumes:
  mysql_data: